"""Added user refreshtoken relationshit

Revision ID: 215ab92a387b
Revises: 45b9c54d3aac
Create Date: 2025-12-13 00:16:36.905411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215ab92a387b'
down_revision = '45b9c54d3aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created')

    # ### end Alembic commands ###
