"""Resend email

Revision ID: 55e14c80ad53
Revises: 77da9a0d5661
Create Date: 2026-01-08 20:50:44.150465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e14c80ad53'
down_revision = '77da9a0d5661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resent_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_verification_tokens', schema=None) as batch_op:
        batch_op.drop_column('resent_count')

    # ### end Alembic commands ###
