name: Account Services Pipeline
run-name: ${{ github.workflow}}- ${{ github.run_id }} by ${{ github.actor }}

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - "account-service/**"
      - ".github/workflows/cicd.yaml"
  pull_request:
    branches:
      - main
      - feature/*

defaults:
  run:
    working-directory: ./account-service

jobs:
  ci_build_test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - run: ls -a

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py') --exit-zero

      - name: Run tests
        run: |
          python -m pytest

      - run: ls -a

      - name: Docker build
        run: |
          docker build -t account-service-test .

      - name: build secrets
        run: |
          echo "Creating env files for docker compose"

          echo "${{ secrets.ENV }}" >> .env
          echo "${{ secrets.ENVDB }}" >> .env.db
          echo "Env files created"
          ls -a

      - name: smoke test
        run: |
          docker-compose up -d
          sleep 10
          curl -f -w "%{http_code}" http://localhost:5000/health/ -w "%{http_code}" || exit 1
          docker-compose down

      - uses: atos-actions/clean-self-hosted-runner@v1
        if: ${{ always() }} # Run even if previous steps in the job fail or are canceled

  deploy_dev:
    needs: ci_build_test
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: deploying to dev
        run: |
          echo "Deploying to development environment"
      - uses: atos-actions/clean-self-hosted-runner@v1
        if: ${{ always() }} # Run even if previous steps in the job fail or are canceled
